namespace AutoMythTunnel.Proxy;

public enum EnumPacketType
{
    SERVER_CHAT,
    CLIENT_CHAT,
    SERVER_HEALTH_CHANGE,
    SERVER_SET_POSITION_AND_ROTATION,
    SERVER_RESPAWN,
    SERVER_JOIN_GAME,
    SERVER_ENTITY_PROPERTIES,
    SERVER_ENTITY_METADATA,
    CLIENT_USE_ENTITY,
    SERVER_ANIMATION,
    SERVER_DISCONNECT,
}